<?php

/*************************************************************************
* This file is part of the MathHub.info System  (http://mathhub.info).   *
* It is hosted at https://github.com/KWARC/MathHub                       *
* Copyright (c) 2015 by the KWARC group (http://kwarc.info)              *
* Licensed under GPL3, see http://www.gnu.org/licenses/gpl.html          *
**************************************************************************/

/**
 * Implementation of hook_captcha().
 */
function mathhub_captcha_captcha($op, $captcha_type='') {

  switch ($op) {
    case 'list':
      return array('MathHub CAPTCHA');
    case 'generate':
      if ($captcha_type == 'MathHub CAPTCHA') {
        //math symbols
        $symbols = array();
        $symbols[] = array('math' => "&#8968;&#960;&#8969;", 'value' => 4, 
          'desc' => "<a target='_blank' href='https://mathhub.info/smglom/numberfields/ceilingfloor.en.omdoc'>ceiling</a> of Pi");
        $symbols[] = array('math' => "&#8970;&#960;&#8971;", 'value' => 3, 
          'desc' => "<a target='_blank' href='https://mathhub.info/smglom/numberfields/ceilingfloor.en.omdoc'>floor</a> of Pi ");
//        $symbols[] = array('math' => "&#8968;e&#8969;", 'value' => 3, 'desc' => "ceiling of Euler's Number");
//        $symbols[] = array('math' => "&#8970;e&#8971;", 'value' => 2, 'desc' => "floor of Euler's Number");
        
        $first = mt_rand(2,7);
        $second = mt_rand(0, count($symbols) - 1);
        $third = mt_rand(1,9);
        $question = "<div>\"" . $first . " &#215; " . $symbols[$second]['math'] . " &#43; x\"," . 
                    " where x is $third and " . $symbols[$second]['math'] . " is " . $symbols[$second]['desc'] . "</div>";
        $answer = $first *  $symbols[$second]['value'] + $third;
        $captcha = array();
        $captcha['solution'] = $answer;
        $captcha['form']['captcha_response'] = array(
          '#type' => 'textfield',
          '#title' => 'Enter the result of the computation below',
          '#description' => "Compute: " . $question,
          '#required' => TRUE,
        );
        return $captcha;
      }
      break;
  }
}