<?php
require_once 'oaff.logger.php';
require_once 'oaff.features.php';
require_once 'oaff.admin.php';
require_once 'oaff.html_utils.php';

/**
 * Implements hook_menu
 * Adds entries for OAFF calculhmac(clent, data)onfiguration and auto-loading nodes (from location set in config) 
 */
function oaff_menu() {
  $items = array();
  $items['admin/config/content/oaff'] = array(
    'title' => 'OAFF configuration',
    'description' => 'Configure OAFF',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('oaff_config_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['mh/initialize-nodes'] = array(
    'title' => "Initialize Nodes",
    'page callback' => 'oaff_create_nodes',
    'access callback' => 'oaff_admin_access',
    'menu_name' => 'navigation'
  );
  $items['mh/help'] = array(
    'title' => "Help",
    'page callback' => 'oaff_help_page',
    'access callback' => true,
    'menu_name' => 'navigation'
  );
  $items['mh/content'] = array(
    'title' => "MMT Content",
    'page callback' => 'oaff_dynamic_content_page',
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );
  $items['node/%node/svg'] = array(
    'title' => 'SVG',
    'page callback' => 'oaff_node_svg',
    'page arguments' => array(1),
    'access callback' => 'oaff_access_by_node_type',
    'access arguments' => array(1, array(1=>'oaff_doc')),
    'weight' => 0,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  $items['node/%node/omdoc'] = array(
    'title' => 'OMDoc',
    'page callback' => 'oaff_node_omdoc',
    'page arguments' => array(1),
    'access callback' => 'oaff_access_by_node_type',
    'access arguments' => array(1, array(1=>'oaff_doc')),
    'weight' => 0,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  $items['node/%node/source'] = array(
    'title' => 'Source',
    'page callback' => 'oaff_node_source',
    'page arguments' => array(1),
    'access callback' => 'oaff_access_by_node_type',
    'access arguments' => array(1, array(1=>'oaff_doc')),
    'weight' => 0,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  oaff_features_menu($items);
  oaff_admin_menu($items);
  return $items;
}

function oaff_dynamic_content_page() {
  $uri = $_GET["uri"];
  drupal_add_js("$ = jQuery;", "inline");
  $response = mmt_get($uri);
  return $response;
}

function oaff_permission() {
  return array(
    'administer mathhub' => array(
      'title' => t("Administer MathHub"),
      'description' => t("Perform administration and devel tasks in MathHub"),
    ),
  );
}

function oaff_help_page() {
  $out = '<p> Using MathHub should be documented on the <a href="/">homepage</a>. For any other issues, use the links below. </p>';
  $out .= '<div>';
  $out .= '<a href="mailto:m.iancu@jacobs-university.de?Subject=[MathHub]" target="_blank" class="btn btn-primary"> Contact a human </a> ';
  $out .= '<a href="http://github.com/KWARC/MathHub/issues/new?issue" target="_blank" class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Requires Authentication"> Report an Issue </a> (click <a href="https://github.com/KWARC/MathHub/issues/" target="_blank">here</a> for known issues)';
  $out .= '</div>';
  return $out;
}

/**
 * implements hook_field_formatter_info, declares the formatter types implemented 
 * by this module.
 * Currently:  
 *   'mmt_formatter' which formats mmt content 
 */
function oaff_field_formatter_info() {
   return array(
    'oaff_help_formatter' => array(
      'label' => t('Formatter of Help Files'),
      'field types' => array('vfs_file'),
    ),
  );
}

function oaff_autogenerate_top_doc() {
  $html = "";
  $oaff_config= variable_get('oaff_config');
  $top_info = $oaff_config['top'];
  $desc = ""; //default
  if (isset($top_info['description'])) {
    $desc = $top_info['description'];
  }
  $resp = ""; //default
  if (isset($top_info['responsible'])) {
    $resp = $top_info['responsible'];
  }
  $html .= $desc;
  $html .= $resp;
  //adding group list
  $groups = planetary_repo_list("");
  $elems = array();
  $html .= "<ul>";
  foreach ($groups as $group) {
    if (planetary_repo_is_dir($group) && $group[0] != '.' && $group != "meta" && drupal_lookup_path('source', $group)) {
      $group_info = $oaff_config['groups'][$group];
      $name = $group;
      if (isset($group_info['title'])) {
        $name = $group_info['title'];
      }
      $teaser = "";
      if (isset($group_info['teaser'])) {
        $teaser = $group_info['teaser'];
      }
      $html .= '<li> <a href="/' . $group . '">' . $name .  ' </a>  <small> '. $teaser .' </small></li>';

    }
  }
  $html .= "</ul>";
  
  return $html;
}

function oaff_autogenerate_group_doc($group) {
  $html = "";
  $oaff_config= variable_get('oaff_config');
  $group_info = $oaff_config['groups'][$group];
  $desc = ""; //default
  if (isset($group_info['description'])) {
    $desc = $group_info['description'];
  }
  $resp = ""; //default
  if (isset($group_info['responsible'])) {
    $resp = $group_info['responsible'];
  }
  $html .= $desc;
  $html .= $resp;
  //adding archive list
  $archives = planetary_repo_list($group);
  $html .= '<ul>';
  foreach ($archives as $archive) {
    $arch_path = oaff_join_path(array($group, $archive));
    if (planetary_repo_is_dir($arch_path) && $archive[0] != '.' && $archive != "meta-inf" && drupal_lookup_path('source', $arch_path)) { //valid archive
      $oaff_config = variable_get('oaff_config');
      $arch_info = $oaff_config['archives'][$arch_path];
      $name = $arch_path; // default
      if (isset($arch_info['title'])) {
        $name = $arch_info['title'];
      }
      $teaser = ""; // default    
      if (isset($arch_info['teaser'])) {
        $teaser = $arch_info['teaser'];
      }

      $html .= '<li> <a href="/' . $arch_path . '">' . $name .  ' </a>  <small> '. $teaser .' </small></li>';
    }
  }
  $html .= "</ul>";
  return $html;
}

function oaff_autogenerate_archive_doc($group, $archive) {
  $arch_path = oaff_join_path(array($group, $archive));
  $html = "";
  $oaff_config= variable_get('oaff_config');
  $arch_info = $oaff_config['archives'][$arch_path];
  $desc = ""; //default
  if (isset($arch_info['description'])) {
    $desc = $arch_info['description'];
  }
  $resp = ""; //default
  if (isset($arch_info['responsible'])) {
    $resp = "<p><strong>Responsible: </strong>" . $arch_info['responsible'] . "</p>";;
  }
  $html .= $desc;
  $html .= $resp;
  $content_path = oaff_join_path(array($group, $archive, 'export/planetary/narration', '.html'));
  $html .= "<div>" . planetary_repo_load_file($content_path) . "</div>";
 
  //$html .= "<ul><li><a href=\"/$group/$archive/source\">Content</a> </li>
  //             <li><a href=\"http://gl.mathhub.info/$group/$archive\" target=\"_blank\">Sources</a> </li>
  //              <li><a href=\"/mh/common-errors?&groups=$group&archives=$archive\">Errors</a> </li></ul>";
  return $html;
}


/**
 * implements hook_filed_formatter view, 
 * @param $entity_type The type of $entity
 * @param $entity The entity being displayed
 * @param $field The field structure
 * @param $instance The field instance
 * @param $langcode The language associated with $items
 * @param $items Array of values for this field
 * @param $display The display settings to use, as found in the 'display' entry of instance definitions
 */
function oaff_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'oaff_help_formatter':
      $lang = $entity->language;
      foreach ($items as $delta => $item) {
        $location = $item['path'];
        if (planetary_repo_stat_file($location)) {
          $content = planetary_repo_load_file($location);
          try {
            $content = str_replace('xmlns=', 'ns=', $content); 
            $xml = new SimpleXMLElement($content, LIBXML_NOERROR);
            $titles = $xml->title;
            $frags = $xml->xhtmlfrag;
            if (count($titles) != 1 || count($frags) != 1) {
              throw new Exception("Invalid help node format");
            }
            $title = (string)$titles[0];
            $markup = "";
            foreach($frags[0]->children() as $elem) {
              $markup .= $elem->asXML();
            }
            //setting title to be later used for teaser
            $entity->title = $title;
            node_save($entity);
            drupal_set_title($title);
          } catch (Exception $e) {
            drupal_set_message("Invalid help node format, treating as plain html fragment", 'warning');
            $markup = $content;
          }
        } else {
          $segs = explode("/", $location); //format is "$base" / "help" / "index.html"
          if ($segs[0] == 'meta') { //at top level
            $markup = oaff_autogenerate_top_doc();
          } else if ($segs[1] == 'meta-inf') { //at group level
            $group = $segs[0];
            $markup = oaff_autogenerate_group_doc($group);
          } else { //at archive level
            $group = $segs[0];
            $archive = $segs[1];
            $markup = oaff_autogenerate_archive_doc($group, $archive);
          }
        }
        $element[$delta] = array(
          "#type" => "container",
          "#attributes" => array(),
          "content" => array(
            '#markup' => $markup,
          )
        );
      }
      break;
    }
  return $element;
}

function oaff_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'oaff_doc_node_form') {
    $nid = $form['#node']->nid;
    $elems = oaff_get_language_group($nid);
    $lang_dict = array('und' => 'base', 'de' => 'deutsch', 'en' => 'english');

    if (isset($_GET['start']) && isset($_GET['end'])) {
      $start = $_GET['start'];
      $end = $_GET['end'];
      $lang = $lang_dict[$form['#node']->language];
      drupal_add_js('
        jQuery(function() {
          var mytxt = jQuery("#edit-' . $lang .' .form-textarea").get(0);
          mytxt.focus();
          mytxt.setSelectionRange(' .$start. ',' .$end.');
        });
        ', 'inline');
    }

    // sorting alphabetically (excluding extension)
    usort($elems, function($a, $b) {
      return strcmp(pathinfo($a->location)['filename'], pathinfo($b->location)['filename']);
    });
    $bid = $elems[0]->lid; // based doc

    $form['variants'] = array(
      '#type' => 'hidden',
      '#value' => array(),
    );  
    foreach ($elems as $elem) {
      $location = $elem->location;
      $lid = $elem->lid;
      $path_info = oaff_get_path_info($location);
      $lang = $lang_dict[$path_info['lang']];
      $form['variants']['#value'][] = $lang;
      if ($bid == $lid) {
        $form['module'] = array(
        '#type' => 'textfield',
        '#title' => 'Module Name',
        '#default_value' => $path_info['base_module'],
        '#disabled' => true,
        '#description' => t(' The base name of module'),
      );
      }

      $form['content'][$lang] = array(
          '#type' => 'fieldset',
          '#collapsible' => true,
          '#title' => $lang,
          '#collapsed' => ($nid != $lid),
          '#tree' => true,
      );
      $form['content'][$lang]['location'] = array(
        '#type' => 'hidden',
        '#value' => $location,
        );
      $form['content'][$lang]['body'] = array(
        '#type' => 'text_format',
        '#title' => 'Body',
        '#format' => 'stex',
        '#default_value' => planetary_repo_load_file($location),
        '#description' => t(' The body of the ' .  $lang . ' language version '),
      ); 
    }
    unset($form['field_external']);
    unset($form['title']);
    $form['actions']['submit']['#submit'] = array('oaff_mathhub_doc_act');
    $form['#submit'] = array('oaff_mathhub_doc_submit');
  }
}



function oaff_mathhub_doc_submit($form, $form_state) {
}


function oaff_mathhub_doc_act($form, $form_state) {
  $variants = $form_state['values']['variants'];
  foreach ($variants as $variant) {
    $location = $form_state['values'][$variant]['location'];
    $body = $form_state['values'][$variant]['body']['value'];
    if ($form['content'][$variant]['body']['#default_value'] != $body) { // something changed
      planetary_repo_save_file($location, $body);
    }
  }
  $nid = $form['#node']->nid;
  $alias = drupal_get_path_alias('node/' . $nid);
  drupal_goto($alias);
}

function oaff_get_language_group($nid) {
  // getting bid
  $result = db_select('oaff_node_lang_groups', 'g')
      ->fields('g', array("bid", "location"))
      ->condition('lid', $nid, '=')
      ->execute()
      ->fetchAssoc();
  if (isset($result['bid'])) {
    $bid = $result['bid'];
  }
  $result = db_select('oaff_node_lang_groups', 'g')
      ->fields('g', array("lid", "location"))
      ->condition('bid', $bid, '=')
      ->execute()
      ->fetchAll();

  return $result;
}

function oaff_contextual_basic($form, &$form_state) {
  $form = array();
  
  return $form;
}

function oaff_contextual_info($form, &$form_state, $key) {
  $form = array();
  
  $result = "test";
  
  $form["log"] =
    array(
          "#markup" => "<pre>". $result . "</pre>",
          );

  $form["result"] =
    array(
          "#markup" => "<pre>". $result . "</pre>",
          );

  return $form;
}

/**
 * Function to setup OAFF-specific functionality (CSS & JS) on page
 * OAFF-feature modules (e.g. MMT) define their own initialize methods 
 * to load further features (e.g. JOBAD modules)
 * Typically called from hook_node_view (i.e. for OAFF, oaff_node_view)
 * @param $location Path
 * @param $text_format Text format
 */
function oaff_initialize($location = NULL, $text_format = "") {
    if ($location != NULL) {
      // oaff_initialize
      $pathinfo = oaff_get_path_info($location);
      $archive = $pathinfo['archive'];
      $group = $pathinfo['group'];
      $rel_path = $pathinfo['rel_path'];
      
      //adding data as js variables (used by JS/JOBAD modules)
      drupal_add_js("var oaff_node_group = '$group';", "inline");
      drupal_add_js("var oaff_node_archive = '$archive';", "inline");
      drupal_add_js("var oaff_node_rel_path = '$rel_path';", "inline");      

      // get list of all filters used in $text_format
      $filter_list = filter_list_format($text_format);
      //TODO: HACK, fix this later
      if ($pathinfo['dimension'] == "META-INF") {
        $filter_list[] = 'mmt-presentation';
      }
      /* CSS */
      $mmt_path = drupal_get_path('module', 'mmt');
      $mmt_config = variable_get('mmt_config');
      $mmt_url = $mmt_config['mmturl'];  

      // add js depending on filter activated for $text_format
      foreach ($filter_list as $filter => $value) {
        switch ($filter) {
          case 'mmt-presentation':
            drupal_add_css($mmt_path . '/css/mmt.css', array('weight' => PHP_INT_MAX, 'every_page' => false));
            // mmt js libs
            drupal_add_js($mmt_path . '/utils/mmt-html.js', 'file', array('cache' => false));
            drupal_add_js($mmt_path . '/utils/mmt-planetary.js', 'file', array('cache' => false));
            drupal_add_js($mmt_path . '/utils/planetary-localization.js', 'file', array('cache' => false));

            drupal_add_js($mmt_path . '/utils/mathml.js', 'file', array('cache' => false));
            jobad_add_module($mmt_path . '/jobad/planetary-navigation.js', "kwarc.mmt.planetary.navigation");
            jobad_add_module($mmt_path . '/jobad/ontology-navigation.js', "kwarc.mmt.ontology.navigation");
            jobad_add_module($mmt_path . '/jobad/hovering.js', "kwarc.mmt.hovering");
            jobad_add_module($mmt_path . '/jobad/planetary-gitlab.js', "kwarc.mmt.planetary.gitlab");

            if (isset($value->settings['mmt_style']) 
              && $value->settings['mmt_style'] == 'html') {
              jobad_add_module($mmt_path . '/jobad/interactive-viewing.js', "kwarc.mmt.intvw");
            }
            break;

          case 'local-compilation':
            drupal_add_css($mmt_path . '/css/latexml.css', array('weight' => PHP_INT_MAX, 'every_page' => false));
            break;

          default:
            break;
        }
      }

      /* JavaScript */
      drupal_add_js('var mmtUrl = "' . $mmt_url . '";', 'inline');
      // if search enabled
      // jobad_add_module($mmt_path . '/jobad/search.js', "kwarc.mmt.search");
    }  

    libraries_load("jobad");
    // modules are loaded in specific oaff extensions (e.g. MMT)
    jobad_add_module("/sites/all/libraries/jobad/modules/core/mathjax.mathjax.js", "mathjax.mathjax");//a
    
    $inst_name = jobad_initialize();
    //mmt_initialize(); //should be before -- currently called from mmt_node_view hook instead
    return $inst_name; 
}

/**
 * Implements hook_node_view
 * @param $node The node that is being assembled for rendering.
 * @param $view_mode The $view_mode parameter from node_view() (e.g. "full").
 * @param $langcode The language code used for rendering.
 */
function oaff_node_view($node, $view_mode, $langcode) {
  if ($view_mode != "full")
		return;
  
  $oaff_config = variable_get('oaff_config');
  //handling node rendering
  $compiled_node_types = $oaff_config['compiled_node_types'];
  $all_node_types = $oaff_config['all_node_types'];

  if (drupal_get_path_alias("node/" . $node->nid) == 'mh/glossary') { //special handling for the glossary node
    $markup = file_get_contents("/var/data/localmh/MathHub/glossary.html");
    //loading js/css manually for the glossary, not using oaff initialize
    $mmt_path = drupal_get_path('module', 'mmt');
    $oaff_path = drupal_get_path('module', 'oaff');
    // basics
    drupal_add_js($oaff_path . '/scripts/glossary.js', 'file', array('cache' => false));
    drupal_add_css($oaff_path . '/css/glossary.css', array('weight' => PHP_INT_MAX, 'every_page' => false));
    drupal_add_css($mmt_path . '/css/mmt.css', array('weight' => PHP_INT_MAX, 'every_page' => false));
    drupal_add_css($mmt_path . '/css/latexml.css', array('weight' => PHP_INT_MAX, 'every_page' => false));

    // mmt js libs
    drupal_add_js($mmt_path . '/utils/mmt-html.js', 'file', array('cache' => false));
    drupal_add_js($mmt_path . '/utils/planetary-localization.js', 'file', array('cache' => false));
    drupal_add_js($mmt_path . '/utils/mmt-planetary.js', 'file', array('cache' => false));
    drupal_add_js($mmt_path . '/utils/mathml.js', 'file', array('cache' => false));
    //jobad modules 
    jobad_add_module($mmt_path . '/jobad/planetary-navigation.js', "kwarc.mmt.planetary.navigation");
    jobad_add_module($mmt_path . '/jobad/ontology-navigation.js', "kwarc.mmt.ontology.navigation");
    jobad_add_module($mmt_path . '/jobad/hovering.js', "kwarc.mmt.hovering");
    jobad_add_module("/sites/all/libraries/jobad/modules/core/mathjax.mathjax.js", "mathjax.mathjax");
    
    //mmt url   
    $mmt_config = variable_get('mmt_config');
    $mmt_url = $mmt_config['mmturl'];  
    drupal_add_js('var mmtUrl = "' . $mmt_url . '";', 'inline');

    libraries_load("jobad");
    $inst_id = jobad_initialize();

    $node->content['body'][0]['#markup'] = '<div id="' . $inst_id . '" class="bootstrap" >' . $markup . '</div>';
  }

  // actually presenting
  if (in_array($node->type, $compiled_node_types)) {
    //getting node data
    $location = $node->field_external['und']['0']['path'];
    $pathinfo = oaff_get_path_info($location);
    $status = oaff_get_errors($node->nid);

    $fatals = oaff_get_errors($node->nid, array(3));
    $omdoc_location = $pathinfo['alias'];
    $omdoc = ""; //default
    if (planetary_repo_stat_file($omdoc_location)) { //omdoc exists
      $omdoc = planetary_repo_load_file($omdoc_location);
    }
      
  	if ($fatals) { // fatals exists for this node => time to report errors  
      $location = $node->field_external['und']['0']['path'];
      $source = planetary_repo_load_file($location);
      $output = oaff_mark_source_errors(check_plain($source), $node->nid, $status);
      $output .= oaff_get_log_html($status);
      $node->content['field_external'][0]['content']['#markup'] = $output;      
    } else {
      $location = $node->field_external['und']['0']['path'];
      $source = planetary_repo_load_file($location);
    	$content = $node->content['field_external'][0]['content']['#markup'];
      $node->content['field_external'][0]['content']['#markup'] = $content . oaff_get_log_html($status);
	  }
  }

  // case for normal nodes
  // settings breadcrumb

  if (in_array($node->type, $all_node_types)) {
    // add variable to set the language of context menu
    if (isset($node->language) && $node->language != 'und')
      drupal_add_js("var language = \"" . $node->language . "\";", "inline");
    $location = $node->field_external['und']['0']['path'];
    oaff_set_breadcrumb($node->nid);
    $inst_id = oaff_initialize($location, oaff_get_node_filter_format($node));
    $content = $node->content['field_external'][0]['content']['#markup'];
    $node->content['field_external'][0]['content']['#markup'] = 
        '<div id="' . $inst_id . '" class="bootstrap" >' . $content . '</div>';
  }

}

/**
* Return the machine name of text format of the node
* @param $node Node
*/
function oaff_get_node_filter_format($node) {
  return $node->field_external['und'][0]['filter'];
}

// if option set to 0 returns raw svg content
function oaff_svg_html($pathinfo) {
  $relpath = $pathinfo['rel_path'];
  $args = explode(".", $relpath);
  if (count($args) == 1) {
    $svgname = oaff_join_path(array($relpath, ".svg"));
  } else {
    array_pop($args);
    $svgname = implode(".",$args) . ".svg";
  }
  $svg_content = planetary_repo_load_file(oaff_join_path(array($pathinfo['group'], $pathinfo['archive'], "export/svg/narration", $svgname)));
  return $svg_content; 
}


function oaff_save_error_status($nid, $compiler, $status) {
  $path = drupal_get_path_alias('node/' . $nid);
  $pathinfo = oaff_get_path_info($path);
  $group = $pathinfo['group'];
  $archive = $pathinfo['archive'];
  $type_map = array("Info" => 0, "Warning" => 1, "Error" => 2, "Fatal" => 3);
  if ($status['conversion'] != -1 ) { // -1 means log not re-read
    //delete old errors -- if any
    db_delete('oaff_errors')
        ->condition(db_and()->condition('nid', $nid)->condition('compiler', $compiler))         
        ->execute();
    //add new ones
    foreach ($status['messages'] as $msg) {
      $short_msg = $msg['shortMsg'];
      if (strlen($short_msg) > 1000) {// limiting size to under 1023 to fit in db
        $short_msg = substr($short_msg, 0, 1000) . " ...";
      }
      $long_msg = $msg['longMsg'];
      if (strlen($long_msg) > 2000) {// limiting size to under 2047 to fit in db
        $long_msg = substr($long_msg, 0, 2000) . " ...";
      }

      $type = $type_map[$msg['type']]; // converting string to integer err format
      $srcref = ""; // default
      if (isset($msg['srcref'])) {
        $srcref .= $msg['srcref']['from']['line'] . "." . $msg['srcref']['from']['col'] . "-" ;
        $srcref .= $msg['srcref']['to']['line'] . "." . $msg['srcref']['to']['col'];
      } 

      $query = db_insert('oaff_errors')
      ->fields(array(
        'nid' => $nid,
        'type' => $type_map[$msg['type']],
        'compiler' => $compiler,
        'mh_group' => $group,
        'mh_archive' => $archive,
        'short_msg' => $short_msg,
        'long_msg' => $long_msg,
        'srcref' => $srcref))
      ->execute();
    }
  }
}
  
function oaff_get_errors($nid, $levels = array(0,1,2,3)) { // by default get all error levels
  $result = db_select('oaff_errors', 'e')
    ->fields('e')
    ->condition(db_and()->condition('nid', $nid, '=')->condition('type', $levels, 'IN'))
    ->execute()
    ->fetchAll();
  return $result;
}



function oaff_get_log_html($status) {
  $color_catalog = array(0 => "#9999FF", 1 => "#BBBB00", 2 => "#FF6666", 3 => "#FF2222");
  $error_catalog = array(0 => "Info", 1 => "Warning", 2 => "Error", 3 => "Fatal");
  $conv_status_catalog = array(0 => "<span style='color:#9999FF'>Conversion Succeeded<span>", 
                               1 => "<span style='color:#BBBB00'>Conversion Succeeded (with warnings)<span>", 
                               2 => "<span style='color:#FF6666'>Conversion Succeeded (with errors)<span>", 
                               3 => "<span style='color:#FF2222'>Conversion Failed<span>");


  $conversion_status = 0; //assuming success
  $errors = array(0 => array(), 1 => array(), 2 => array(), 3 => array());
  $data_title_content = array(); // store (title, content) dictionaries

  foreach ($status as $msg) {
    $errors[3 - $msg->type][] = $msg; //reversing things to show more severe errors first
    $conversion_status = max($conversion_status, $msg->type);
  }

  // if success don't show log
  if ($conversion_status == 0) {
    $log = '<hr/> <div> <p> ' . $conv_status_catalog[$conversion_status] .'</p></div>';
  } else {
    // creating log
    $log = '<hr/> <div> <p> ' . $conv_status_catalog[$conversion_status] . ' <a style="cursor:pointer;" onclick="if (jQuery(this).html() == \'Show Log\') {jQuery(this).html(\'Hide Log\')} else {jQuery(this).html(\'Show Log\')}; jQuery(\'#oaff_error_log\' ).toggle( \'fold\' );" >Show Log</a> ';
    $log .= '</p> </div>';
    $log .= '<div id="oaff_error_log" style="display: none;"><ul>';
    foreach ($errors as $err_level) {
      foreach($err_level as $msg) {
        $log .= "<li>";
        $srcref_msg = '';
        if ($msg->srcref) {
          $srcref_msg .= 'at ' . $msg->srcref;
        }

        $short_msg = check_plain($msg->short_msg);
        $long_msg = check_plain($msg->long_msg);
        $color = $color_catalog[$msg->type];
        $log .= "<p><b>$msg->compiler</b> <u style=\"color:{$color}\"> {$error_catalog[$msg->type]} $srcref_msg </u> : $short_msg </p>";
        $log .= "<pre> $long_msg </pre>";
        $log .= "</li>"; 
      }
    }
    $log .= "</ul></div>";
  }
  return $log;
}



/**
 * function to mark errors, annotates source string with error information
 * @param $source the source string
 * @param $nid the node id
 * @param $status the error array 
 * @return the processed string (with errors marked)
 */
function oaff_mark_source_errors($source, $nid, $status) {
  $error_catalog = array(0 => "Info", 1 => "Warning", 2 => "Error", 3 => "Fatal");

  // separate errors by compilers
  $errors_compiler = array();
  foreach ($status as $key => $value) {
    if (!isset($errors_compiler[$value->compiler]))
      $errors_compiler[$value->compiler] = array(); 
    $errors_compiler[$value->compiler][] = $value; 
  }

  // collect unique references
  $srcrefs = array();
  foreach ($status as $key => $error) {
    if ($error->srcref != "") {
      $pcs = explode("-", $error->srcref);
      $srcrefs[$pcs[0]] = 0; 
      
      //
      $to = explode(".", $pcs[1]);
      $to_line = $to[0];
      $to_column = (string) (1 + (int) $to[1]); 
      $srcrefs[(implode(".", array($to_line, $to_column)))] = 0;
    }
  }

  $srcrefs = array_keys($srcrefs);
  sort($srcrefs);

  // separating to the array where keys are line numbers
  $refs = array();
  foreach ($srcrefs as $srcref) {
    $slices = explode(".", $srcref);
    $ref = (int) $slices[0];
    if (!isset($refs[$ref]))
      $refs[$ref] = array();
    $refs[$ref][] = (int) $slices[1];
  }

  $lines = explode("\n", $source);
  $line_offsets = array(0);
  $i = 0;
  $new_lines = array();
  while ($i < count($lines)) {
    $line_offsets[] = $line_offsets[$i] + strlen($lines[$i]);
    $i += 1;
  }

  // add spans to divide code 
  function tokenize_source($source, $srcref) {
    $lines = explode("\n", $source);
    $line_offsets = array(0);
    $i = 0;
    $close_tag = false;
    foreach ($srcref as $line_num => $char_nums) {
      $line = $lines[$line_num - 1];
      $new_line = "";
      if ($char_nums[0] != 1)
        $new_line .= substr($line, 0, $char_nums[0] - 1);
      if ($close_tag) {
        $new_line .= "</span>";
        $close_tag = false;
      }
      for ($j = 0; $j < count($char_nums) - 1; $j++) {
        $new_line .= "<span id=\"ref_{$line_num}_{$char_nums[$j]}\">";
        $new_line .= substr($line, $char_nums[$j] - 1, $char_nums[$j+1] - $char_nums[$j]);
        $new_line .= "</span>";
      }
      $new_line .= "<span id=\"ref_{$line_num}_" . $char_nums[count($char_nums)-1] . "\">";
      $new_line .= substr($line, $char_nums[count($char_nums)-1]-1);
      $close_tag = true;
      $lines[$line_num - 1] = $new_line;
    }
    $source = implode("\n", $lines);
    if ($close_tag)
      $source .= "</span>"; 
    return $source;
  }


  $source = tokenize_source($source, $refs);

  $out = "";

  // get all values from the array that are between $from and $to, including $from
  // $array should be sorted in increasing order
  function get_middle_elements($array, $from, $to) {
    $out = array();
    $in_middle = false;
    foreach ($array as $key => $value) {
      if ($value >= $to)
        break;
      if ($value == $from) {
        $in_middle = true;
      }
      if ($in_middle)
        $out[] = $value;
    }
    return $out;
  }

  $notification_counter = 0;
  $inst_id = oaff_initialize();
  foreach ($errors_compiler as $compiler => $errors) {
    $register = "";
    $unregister = "";
    $selector = "";
    $out .= '
    <label class="btn btn-primary btn-sm">
      <input id="'. $compiler . '" type="checkbox"> '. $compiler . ' 
    </label>';
    foreach ($errors as $msg) {
      // errors with references
      if ($msg->srcref) {
        $parts = explode("-",$msg->srcref);
        $from_parts = explode(".",$parts[0]);
        $to_parts = explode(".", $parts[1]);

        $from_line = $from_parts[0]; 
        $from_col = $from_parts[1];
        $from = $line_offsets[$from_line - 1] + $from_col; //-1 since arrays start at 0, line numbers at 1
        $to_line = $to_parts[0];
        $to_col = $to_parts[1];
        $to = $line_offsets[$to_line - 1] + $to_col; //-1 since arrays start at 0, line numbers at 1
        
        
        // select several spans
        $ids = get_middle_elements($srcrefs, $parts[0], $parts[1]);
        $selector ="";
        $last_key = count($ids) - 1;
        foreach ($ids as $key => $id) {
          $selector .= "#ref_" . str_replace(".", "_", $id);
          if ($key != $last_key)
            $selector .= ", ";
        }
        $edit_query = '?start=' . $from . '&end=' . $to;
      } else {
        // errors w/o references assign to whole source code
        $selector = "#ref_general";
        $edit_query = "";
      }
      $register .= '
        n'. $notification_counter . ' = ' . $inst_id .'.Sidebar.registerNotification(jQuery("' . $selector . '"), 
            { 
              "class": "' . strtolower($error_catalog[$msg->type]) .'",
              "text": "' .  str_replace('"', "'", $msg->short_msg) . '", 
              "click": function() {
                window.open("/node/'.$nid.'/edit' . $edit_query . '");
              },
              "trace":true,
          });';
      $unregister .= '
          '. $inst_id .'.Sidebar.removeNotification(n' . $notification_counter . ');'; 
      $notification_counter++;
    }

    // js to constantly check checkboxes status
    $sidebar = "jQuery(function(){
       jQuery('#{$compiler}').change(function(){
          if(jQuery(this).is(':checked')) {
              $register
          } else {
              $unregister
          }
       });
    });";

    drupal_add_js($sidebar, array('type' => 'inline', 'weight' => 100));
  }

  // if there are errors add them to outpu
  if ($out != "") {
    $out = '<div>
    <label> Compilers </label> 
    <div class="btn-group" data-toggle="buttons">'.
      $out .'
    </div>
</div><br/>';
  }

  $out .= "<div id=\"$inst_id\"><pre id=\"ref_general\">\n" . $source . '\n</pre></div>';
  return $out;
}


// ------------------------------- OAFF Autoload Crawler -------------------------------- \\

/**
 * Creates nodes for all documents in planetary_repo path where there is a oaff-connected content type 
 * associated with that format (based on file extension).  (All set up in OAFF configuration)
 */
function oaff_create_nodes() {
  $oaff_config = variable_get('oaff_config');
  $oaff_config['latest_nodes'] = 0;
  $oaff_config['deleted_nodes'] = 0;
  variable_set('oaff_config', $oaff_config);
  _oaff_crawler_update_doc_nodes();
  $groups = _oaff_crawler_get_active_archives();
  _oaff_crawler_update_content($groups);
  $oaff_config = variable_get('oaff_config');
  $nr_nodes = $oaff_config['latest_nodes'];
  $nr_del_nodes = $oaff_config['deleted_nodes'];
  if ($nr_nodes == 0) {
    drupal_set_message("Successfully crawled archives, nothing new to import");
  } else {
    drupal_set_message("Successfully created $nr_nodes nodes");
  }
  if ($nr_del_nodes > 0) {
    drupal_set_message("Deleted $nr_del_nodes nodes");
  }
  $out = '<div> <button class="btn btn-primary " onclick="window.location = \'/mh/initialize-nodes\'"> Continue </button> </div> ';
  return $out;
}


/**
 * Crawls the filesystem for documentation nodes (typically html files in meta/inf/help)
 */
function _oaff_crawler_update_doc_nodes() {
  $docs_base = "/meta/inf/doc/help/";
  $files = planetary_repo_list($docs_base);
  foreach ($files as $filename) {
    $pathinfo = pathinfo($filename);
    $name = $pathinfo['filename'];
    $fullname = $pathinfo['basename'];
    $alias = oaff_join_path(array('help', $filename));
    $fpath = oaff_join_path(array($docs_base, $filename));
    $srcpath = drupal_lookup_path('source', $alias);
    if (!$srcpath) {
      if (isset($pathinfo['extension']) && $pathinfo['extension'] == "html") {
        $options = array();
        if ($fpath == "/meta/inf/doc/help/main.html") { //main entry point of documentation
          $options = array("promote" => 1, "sticky" => 1);
        }
        oaff_create_help_node($name, 'help/' . $fullname, $fpath, $options);
      }
    }
  }
}


/**
 * function crawl oaff archives for files to create nodes from (based on extension and OAFF config)
 * is called by oaff_create_nodes
 */
function _oaff_crawler_get_active_archives() {
  $oaff_config = variable_get("oaff_config");
  $oaff_config['top'] = _oaff_get_top_info();
  variable_set('oaff_config', $oaff_config);

  $groups = planetary_repo_list("");
  $active_groups = array();
  
  foreach ($groups as $group) {
    if (planetary_repo_is_dir($group) && $group[0] != '.' && $group != 'meta') {
      $archives = planetary_repo_list($group);
      foreach ($archives as $archive) {
        if (planetary_repo_is_dir(oaff_join_path(array($group, $archive))) && $archive[0] != '.' && $archive != 'meta-inf') {
          $active = _oaff_crawl_archive($group, $archive);

          if ($active) {
            $oaff_config = variable_get("oaff_config");
            $oaff_config['groups'][$group] = _oaff_get_group_info($group);
            variable_set('oaff_config', $oaff_config);
            if (!isset($active_groups[$group])) {
              $active_groups[$group] = array();
            }
            $active_groups[$group][] = $archive;
          }
        }
      }
    }
  }
  return $active_groups;
}


function _oaff_get_top_info() {
 // getting info from manifest
  $mf_path = "meta/inf/MANIFEST.MF";
  $manifest = planetary_repo_load_file($mf_path);
  $mf_lines = explode("\n", $manifest);
  $props = array();//array of archive properties
  foreach ($mf_lines as $line) {
    $pair = explode(":", $line, 2);
    if (count($pair) == 2) { //ignoring invalid (e.g empty) lines 
      $props[$pair[0]] = $pair[1];
      if ($pair[0] == 'description') {
        $desc_file = trim($pair[1]);
        $props[$pair[0]] = planetary_repo_load_file(oaff_join_path(array("meta/inf/", $desc_file)));
      }
    }
  }
  return $props;
}

function _oaff_get_group_info($group) {
  // getting info from manifest
  $mf_path = oaff_join_path(array($group, "meta-inf/MANIFEST.MF"));
  $manifest = planetary_repo_load_file($mf_path);
  $mf_lines = explode("\n", $manifest);
  $props = array();//array of archive properties
  foreach ($mf_lines as $line) {
    $pair = explode(":", $line, 2);
    if (count($pair) == 2) { //ignoring invalid (e.g empty) lines 
      $props[$pair[0]] = $pair[1];
      if ($pair[0] == 'description') {
        $desc_file = trim($pair[1]);
        $props[$pair[0]] = planetary_repo_load_file(oaff_join_path(array($group, "meta-inf", $desc_file)));
      }
    }
  }
  return $props;
}

function _oaff_get_archive_info($group, $archive_path) {
  $oaff_config = variable_get('oaff_config');
  
  // getting info from manifest
  $mf_path = oaff_join_path(array($group, $archive_path, "META-INF/MANIFEST.MF"));
  
  $manifest = planetary_repo_load_file($mf_path);
  $mf_lines = explode("\n", $manifest);
  $docbase = 'http://docs.omdoc.org/default'; // default
  $archive = 'default'; // default
  $props = array();//array of archive properties

  foreach ($mf_lines as $line) {
    $pair = explode(":", $line, 2);
    if (count($pair) == 2) { //ignoring invalid (e.g empty) lines 
      $props[$pair[0]] = $pair[1];
      if (trim($pair[0]) == "narration-base") {
        $docbase = trim($pair[1]);
      } elseif (trim($pair[0]) == "id") {
        $archive = trim($pair[1]);
      } elseif ($pair[0] == 'description') {
        $desc_file = trim($pair[1]);
        $props[$pair[0]] = planetary_repo_load_file(oaff_join_path(array($group, $archive_path, "META-INF", $desc_file)));
      }
    }
  }
  return array('docbase' => $docbase, 'id' => $archive, 'props' => $props);
}

/**
 *  function to crawl one archive for files to create oaff nodes from (based on extension and OAFF config)
 * is called by _oaff_crawl_archives() for each found archive
 * @param $path the VFS folder-path of the archive
 */
function _oaff_crawl_archive($group, $archive_path) { 
  $oaff_config = variable_get('oaff_config');
  $docbases = array();
  if (isset($oaff_config['docbases'])) {
    $docbases = $oaff_config['docbases'];
  }
  $archive_ids = array();
  if (isset($oaff_config['archive_id'])) {
    $archive_ids = $oaff_config['archive_id'];
  }
  if (!isset($archive_ids['archive_id'][$group])) {
    $archive_ids['archive_id'][$group] = array();
  }
  if (!isset($archive_ids['archive_id'][$group][$archive_path])) {
    $archive_ids['archive_id'][$group][$archive_path] = array();
  }

  // getting info from manifest
  $arch_info = _oaff_get_archive_info($group, $archive_path);
  $docbase = $arch_info['docbase'];
  $archive_id = $arch_info['id'];
  $arch_props = $arch_info['props'];
  
  if (isset($oaff_config['formats'][$archive_id])) { //archive enabled
    drupal_set_message("Crawling archive $archive_id."); 
    // crawling archive
    $docbases[$archive_id] = $docbase;
    $oaff_config['docbases'] = $docbases;
    $oaff_config['archive_id'][$group][$archive_path] = $archive_id;
    $arch_fpath = oaff_join_path(array($group, $archive_path));
    $oaff_config['archives'][$arch_fpath] = $arch_props;
    variable_set('oaff_config', $oaff_config);
    return true;
  } else {
    drupal_set_message("Ignoring archive $archive_id because format is not configured. Please update OAFF configuration to enable it.", 'warning');
    return false;
  }
}

function _oaff_crawler_update_content($groups) {
  $oaff_config = variable_get('oaff_config');
  $rid = $oaff_config['libraries_nid'];
  $gids = array();
  foreach ($groups as $group => $archives) {
    $group_help_fpath = oaff_join_path(array($group, 'meta-inf', 'index.html'));
    $srcpath = drupal_lookup_path('source', $group);
    if (!$srcpath) { //node doesn't already exist
      $gid = oaff_create_help_node($group, $group, $group_help_fpath);
    } else {
      $gid = explode("/", $srcpath)[1];
    }
    $gids[] = $gid;
    $aids = array();
    foreach ($archives as $archive) {
      $archive_path = oaff_join_path(array($group, $archive));
      $archive_help_fpath = oaff_join_path(array($group, $archive, 'META-INF', 'index.html'));
      $srcpath = drupal_lookup_path('source', $archive_path);
      if (!$srcpath) {
        $aid =     oaff_create_help_node($archive, $archive_path, $archive_help_fpath);
      } else {
        $aid = explode("/", $srcpath)[1];
      }
      $aids[] = $aid;
      $archive_id = $oaff_config['archive_id'][$group][$archive];
      $srcids = oaff_crawler_update_source_folder($group, $archive, $archive_id, "");
      oaff_update_children($aid, $srcids);
      if ($oaff_config['latest_nodes'] >= 1000) {
        break 2;
      }
    }
    oaff_set_children($gid, $aids);
  }
  oaff_set_children($rid, $gids);
}

function oaff_join_path($arguments) {
  $path = '';
  $args = array();
  foreach ($arguments as $a) {
    if ($a !== '') {
      $args[] = $a;
    }
  }
  $arg_count = count($args);
  for ($i = 0; $i < $arg_count; $i++) {
    $folder = $args[$i];
    if ($i != 0 and $folder[0] == DIRECTORY_SEPARATOR) {
      $folder = substr($folder, 1);
    } 
    if ($i != $arg_count - 1 and substr($folder, -1) == DIRECTORY_SEPARATOR) {
      $folder = substr($folder, 0, -1);
    }
    $path .= $folder;
    if ($i != $arg_count - 1) {
      $path .= DIRECTORY_SEPARATOR;
    }
  }
  return $path;
}

function oaff_crawler_update_source_folder($group, $archive_path, $archive_id, $rel_path) {
  $dimension = "source";
  $extension = "omdoc";
  $oaff_config = variable_get('oaff_config');
  $extension = $oaff_config['extensions'][$oaff_config['formats'][$archive_id]];
  $folder_path = oaff_join_path(array($group, $archive_path, $dimension, $rel_path));
  $cids = array();
  $lang_groups = array();
  $items = planetary_repo_list($folder_path);
  foreach ($items as $item) {
    if ($item[0] != '.' && $item != "all.tex" && $item != "localpaths.tex") { // ignoring hidden files and folders, 
                                                                              // also lmh/stex specific ones  
      $item_path = oaff_join_path(array($folder_path, $item));
      if (planetary_repo_is_dir($item_path)) {
        $frel_path = oaff_join_path(array($rel_path, $item));
        $fcids = oaff_crawler_update_source_folder($group, $archive_path, $archive_id, $frel_path);
        $fid = oaff_make_folder_node($group, $archive_path, $archive_id, $dimension, $frel_path); 
        oaff_update_children($fid, $fcids);              
        $cids[] = $fid;
      } else {
        $pathinfo = oaff_get_path_info($item_path);
        if (isset($pathinfo['extension']) && $pathinfo['extension'] == $extension) {
          $nid = oaff_make_file_node($group, $archive_path, $archive_id, $dimension, $rel_path, $item);
          $cids[] = $nid;
          //language groups -- consider removing
          $base_module = $pathinfo['base_module'];
          if ($pathinfo['lang'] == 'und') { 
            $lang_groups[$base_module]['base'] = $nid;
          } 
          $lang_groups[$base_module]['variants'][] = array('lid' => $nid, 'location' => $item_path);
        } // else ingore 
      }
    }
    $oaff_config = variable_get('oaff_config');
    if ($oaff_config['latest_nodes'] >= 1000) {
      break;
    }
  }
  oaff_set_lang_groups($lang_groups);
  return $cids;
}


function oaff_create_static_node($title, $alias, $content, $show_in_menu = false) {
  $static_node = (object) array(
   'type' => 'page',
   'uid' => 0,
   'created' => strtotime("now"),
   'changed' => strtotime("now"),
   'status' => 1,
   'comment' => 0,
   'promote' => 0,
   'moderate' => 0,
   'sticky' => 0,
   'language' => 'und'
  );

  $static_node->title = $title;
  node_object_prepare($static_node);
  $static_node->body['und']['0'] = array('value' => $content, 'format' => 'full_html');
  node_save($static_node);
  $path_opt = array(
    'source' => 'node/' . $static_node->nid,
    'alias' => $alias,
  );
  path_save($path_opt);
  
  if ($show_in_menu) { //adding menu entry
    $arch_item = array(
      'link_path' => drupal_get_normal_path($alias),
      'link_title' => $title,
      'weight' => 10,
      'menu_name' => 'main-menu'
    );
    $mlid = menu_link_save($arch_item);
    return array('nid' => $static_node->nid, 'mlid' => $mlid);
  } else {
    return array('nid' => $static_node->nid);
  }
}

function oaff_create_help_node($title, $alias, $fpath, $options = array()) {
  $show_in_menu = false;
  if (isset($options['show_in_menu'])) {
    $show_in_menu = $options['show_in_menu'];
  }
  $promote = 0;
  if (isset($options['promote'])) {
    $promote = $options['promote'];
  }
  $sticky = 0;
  if (isset($options['sticky'])) {
    $sticky = $options['sticky'];
  }

  $help_node = (object) array(
   'type' => 'oaff_helpdoc',
   'uid' => 0,
   'created' => strtotime("now"),
   'changed' => strtotime("now"),
   'status' => 1,
   'comment' => 0,
   'promote' => $promote,
   'moderate' => 0,
   'sticky' => $sticky,
   'language' => 'und'
  );

  $help_node->title = $title;
  node_object_prepare($help_node);
  $help_node->field_external['und']['0'] = array('path' => $fpath);
  node_save($help_node);
  $path_opt = array(
    'source' => 'node/' . $help_node->nid,
    'alias' => $alias,
  );
  path_save($path_opt);
  
  if ($show_in_menu) { //adding menu entry
    $arch_item = array(
      'link_path' => drupal_get_normal_path($alias),
      'link_title' => $title,
      'weight' => 10,
      'menu_name' => 'main-menu'
    );
    $mlid = menu_link_save($arch_item);
    return array('nid' => $help_node->nid, 'mlid' => $mlid);
  } else {
    return array('nid' => $help_node->nid);
  }
}

function oaff_make_folder_node($group, $archive_path, $archive_id, $dimension, $rel_path) {
  $fpath = oaff_join_path(array($group, $archive_path, $dimension, $rel_path));
  $title = $archive_id; // default
  if ($rel_path != "") {
    $title = pathinfo($fpath)['filename'];
  }
  $fpath_info = oaff_get_path_info($fpath);
  $node_path = drupal_lookup_path('source', $fpath_info['alias']);
  if (!$node_path) { // node doesn't exist so we create it
    $dpath = $fpath_info['dpath'];
    // creating node
    $nid = oaff_create_node($title, 'und', 'folder', $dpath, $fpath, 'oaff_virtdoc');
    $oaff_config = variable_get('oaff_config');
    $oaff_config['latest_nodes'] += 1;
    variable_set('oaff_config', $oaff_config);
    return $nid;
  } else {
    $fragments = explode("/", $node_path);
    $nid = $fragments[1];
    return $nid;
  }
}

function oaff_make_file_node($group, $archive_path, $archive_id, $dimension, $rel_path, $item) {
  $oaff_config = variable_get('oaff_config');
  $pathinfo = pathinfo($item);
  $module = $pathinfo['filename'];
  $extension = $pathinfo['extension'];
  $lang = 'und'; // default;
  $mod_pathinfo = pathinfo($module);
  if (isset($mod_pathinfo['extension'])) {
    $lang = $mod_pathinfo['extension'];
  }
  $format = $oaff_config['formats'][$archive_id];
  $node_type = $oaff_config['node_types'][$format];
  
  $fpath = oaff_join_path(array($group, $archive_path, $dimension, $rel_path, $item));
  $fpath_info = oaff_get_path_info($fpath);
  $dpath = $fpath_info['dpath'];
  $node_path = drupal_lookup_path('source', $fpath_info['alias']);
  if (!$node_path) { // node doesn't exist so we create it
    $nid = oaff_create_node($module, $lang, $format, $dpath, $fpath, $node_type);   
    $oaff_config['latest_nodes'] += 1; 
    variable_set('oaff_config', $oaff_config);
    return $nid;
  } else {
    $fragments = explode("/", $node_path);
    $nid = $fragments[1];
    return $nid;
  }
}


// TODO fix the redundancy with oaff_crawl_source_folder()
function oaff_create_oaff_doc($fpath, $archive) {
  $oaff_config = variable_get('oaff_config');
  $format = $oaff_config['formats'][$archive];
  $node_type = $oaff_config['node_types'][$format];
  $extension = $oaff_config['extensions'][$format];
  $loc_parts = explode('/', $fpath);
  $file = $loc_parts[count($loc_parts) - 1];
  $parts = explode('.', $file);
  $ext = $parts[count($parts) - 1];
  if ($ext == $extension) {
    $module = $parts[0];
    $lang = 'und'; // default
    if (count($parts) == 3) {
      $lang = $parts[1];
    }
    $path_info = oaff_get_path_info($fpath);
    $dpath = $path_info['dpath']; 
    $nid = oaff_create_node($module, $lang, $format, $dpath, $fpath, $node_type); 
    // updating parent;
    $node = node_load($nid);
    $view = node_view($node, 'teaser');
    $rendered = drupal_render($view);
  
    $base = implode("/", array_slice(explode("/", $dpath), 0, -1));
    $path = drupal_lookup_path("source", $base);
    $parent = menu_get_object("node", 1, $path);    
    // updating parent child table
    oaff_set_children($parent->nid, array($nid));

    // updating parent body 
    $result = db_select('field_data_body', 'f')
      ->fields('f', array("body_value"))
      ->condition('entity_id', $parent->nid, '=')
      ->execute()
      ->fetchAssoc();
    
    $value = $result['body_value'];
    $value .= $rendered;

    db_update('field_data_body') // Table name no longer needs {}
     ->fields(array(
      'body_value' => $value,
     ))
    ->condition('entity_id', $parent->nid, '=')
    ->execute();
    return $nid;
  } else {
    return -1;
  }
}

/**
* Updates children of the nodes and deletes nodes associated
* with deleted files
* @param $pid nid of the parent node
* @param $ncids new children of the parent node
*/
function oaff_update_children($pid, $ncids) {
  // get ids of old children of $pid
  $ocids = oaff_get_children($pid);
  
  // get nids of nodes associated with deleted files/folders
  $deleted_ids = array_diff($ocids, $ncids);
   
  foreach ($deleted_ids as $key => $nid) {
    node_delete($nid);
    db_delete('oaff_node_parents')
    ->condition('cid', $nid)
    ->execute();
  }

  $oaff_config = variable_get('oaff_config');
  $oaff_config['deleted_nodes'] += count($deleted_ids); // count deleted nodes
  variable_set('oaff_config', $oaff_config);

  oaff_set_children($pid, $ncids);
}

/**
* Get children nids of the parent nid
* @param $pid Node id of the parent node
*/
function oaff_get_children($pid) {
  $result = db_select('oaff_node_parents', 'p')
      ->fields('p', array('cid'))
      ->condition('pid', $pid)
      ->execute()
      ->fetchAllAssoc('cid', PDO::FETCH_BOTH);
  
  if (!function_exists('extract_cid')) {
    function extract_cid($el) {
      return $el['cid'];
    }
  }

  $result = array_map('extract_cid', $result);
  return  $result;
}


/**
 * Explicitly save the parent-child relation of oaff nodes in the database (e.g. for building breadcrumb or menu later)
 * @param $pid the node id of the parent node
 * @param $cids the ids of the children 
 */
function oaff_set_children($pid, $cids) {
  foreach ($cids as $cid) {
    db_insert('oaff_node_parents')
      ->fields(array(
        'cid' => $cid,
        'pid' => $pid,
      ))
      ->execute();
  }
}

function oaff_set_mtime($nid, $mtime, $file) {
  $old = oaff_get_mtime($nid, $file);
  if ($old == "") { //not set
    db_insert('oaff_node_mtime')
      ->fields(array(
        'nid' => $nid,
        'mtime' => $mtime,
        'logfile' => $file,
      ))
      ->execute();
  } else { //updating
    db_update('oaff_node_mtime')
      ->fields(array(
        'mtime' => $mtime,
      ))
      ->condition('nid', $nid, '=')
      ->condition('logfile', $file, '=')
      ->execute();
  }
}

function oaff_get_mtime($nid, $file) {
  $result = db_select('oaff_node_mtime', 'm')
      ->fields('m', array("mtime"))
      ->condition('nid', $nid, '=')
      ->condition('logfile', $file, '=')
      ->execute()
      ->fetchAssoc();
  return $result['mtime'];
}

function oaff_get_mtimes($nid) {
  $results = db_select('oaff_node_mtime', 'm')
      ->fields('m', array("mtime", 'logfile'))
      ->condition('nid', $nid, '=')
      ->execute()
      ->fetchAll();
  return $results;
}

function oaff_set_lang_groups($groups) {
  foreach ($groups as $group) {
    $variants = $group['variants'];
    if (isset($group['base'])) {
      foreach ($variants as $variant) {  
        db_insert('oaff_node_lang_groups')
          ->fields(array(
            'bid' => $group['base'],
            'lid' => $variant['lid'],
            'location' => $variant['location'],
          ))
          ->execute();
      }
    }
  }
}


/**
 * function to set breadcrumb when viewing oaff nodes
 * adds, in order, links to OAFF ancestor nodes to the native drupal breadcrumb
 * @param $nid the id of the node for which to construct breadcrumb
 * @param $extra_pids array of node ids the links of which are added to the breadcrumb
 */
function oaff_set_breadcrumb($nid, $extra_pids = array()) {
  $oaff_config = variable_get('oaff_config');
  $l_nid = $oaff_config['libraries_nid'];
  $found_root = false;
  $pids = $extra_pids;
  while (!$found_root) {
    $last = $nid;
    if (count($pids) > 0) {
      $last = $pids[count($pids) - 1];
    }
    $result = db_select('oaff_node_parents', 'c')
      ->fields('c', array("pid"))
      ->condition('cid', $last, '=')
      ->execute()
      ->fetchAssoc();
    if (!isset($result['pid'])) {// not an oaff node
      return 0; // nothing to do
    }
    $pid = $result['pid'];
    $pids[] = $pid;
    if ($pid == $l_nid) {
      $found_root = true;
    }
  }
  $bc_entries = array();
  foreach ($pids as $pid) {
    $result = db_select('node', 'n')
      ->fields('n', array("title"))
      ->condition('nid', $pid, '=')
      ->execute()
      ->fetchAssoc();
    $path = drupal_get_path_alias('node/' . $pid);
    $title = $result['title'];
    $bc_entries[] =  '<a href="/' . $path . '">' . $title . '</a>';
  }
  $bc_entries[] = '<a href="/">Home</a>';
  $new_bc = array_reverse($bc_entries);
  drupal_set_breadcrumb($new_bc);
}

/**
 * create an oaff node, called by _oaff_crawl_dimension_folder 
 * @param $title the node title (module name in smglom)
 * @param $lang, the language of the node
 * @param $format the text format of the node
 * @param $dpath the document path (MMT URI) of the current document 
 * @param $location the physical location of the source file 
 * @param $node_type the type of the node to be created
 * @return the id of the newly created node
 */
function oaff_create_node($title, $lang, $format, $dpath, $location, $node_type) {
  $newnode = (object) array(
   'type' => $node_type,
   'uid' => 0,
   'created' => strtotime("now"),
   'changed' => strtotime("now"),
   'status' => 1, //published
   'comment' => 0, //comments disabled 
   'promote' => 0,
   'moderate' => 0,
   'sticky' => 0,
   'language' => $lang
  );

  $newnode->title = $title;
  $newnode->field_external['und']['0']['path'] = $location;
  $newnode->field_external['und']['0']['filter'] = $format;
  $newnode->field_external['und']['0']['dpath']['value'] = $dpath;

  node_object_prepare($newnode);// necessary ?
  node_save($newnode);
  return $newnode->nid;
}

/**
 * created an article node programmatically, (for OAFF documents corresponding to folders in source)
 * called from _oaff_crawl_source_folder
 * @param $title the title of the article (in principle, name of folder)
 * @param $body the body of the article (constructed based on its contents in _oaff_crawl_source_folder
 * @return the id of the newly created node
 */
function oaff_create_article($title, $body) {
  $newnode = (object) array(
   'type' => 'article',
   'uid' => 0,
   'created' => strtotime("now"),
   'changed' => strtotime("now"),
   'status' => 1,
   'comment' => 2,
   'promote' => 0,
   'moderate' => 0,
   'sticky' => 0,
   'language' => 'und'
  );
  $newnode->title = $title;
  $newnode->body['und'][0]['value'] = $body;
  $newnode->body['und'][0]['summary'] = $body;  
  $newnode->body['und'][0]['format'] = 'full_html';  

  node_object_prepare($newnode);// necessary ?
  node_save($newnode);
  return $newnode->nid;
}

// ############################# End OAFF Autoload Crawler ########################### \\

/**
 * implements hook_node_insert, creates an alias path for the node based on its document path (MMT URI) 
 * @param $node the node object to be inserted in the database
 */
function oaff_node_insert($node) {
  $oaff_config = variable_get('oaff_config');
  $oaff_node_types = $oaff_config['compiled_node_types'];
  if (in_array($node->type, $oaff_node_types)) {
    $nid = $node->nid;
    $location = $node->field_external['und']['0']['path'];
    $alias = oaff_get_path_info($location)['alias'];
    oaff_save_path($nid, $alias);
    oaff_save_path($nid, $alias, 'omdoc');
    oaff_save_path($nid, $alias, 'svg');
    oaff_save_path($nid, $alias, 'source');
    oaff_save_path($nid, $alias, 'edit');
  }
}

/**
 * saves a path alias for a node, used by oaff_node_insert
 * @param $nid the node id
 * @param $path the alias to be saved (the MMT URI of the node)
 */ 
function oaff_save_path($nid, $path, $aspect = '') {
  // saving path
  if (substr($path, -1) == '/') {
    $path = substr($path, 0, -1);
  }
  $source = 'node/' . $nid;
  if ($aspect != '') {
    $source = $source . '/' . $aspect;
    $path = $path . '!' . $aspect; 
  }
  $path_opt = array(
    'source' => $source,
    'alias' => $path,
  );
  path_save($path_opt);
}

/** 
 * api for MMT/VFS paths and locations, translated MMT URIs to physical location of source files 
 * @param $dpath the MMT URI
 * @return the physical location of the doc
 */
function oaff_get_location($dpath) {
  $oaff_config = variable_get('oaff_config');
  $docbases = $oaff_config['docbases'];
  foreach ($docbases as $archive => $base) {
    if (strncmp($dpath, $base, strlen($base)) === 0) { // $dpath starts with $base   
      $fragment = substr($dpath, strlen($base) + 1); // +1 removes the connecting slash as in 'base/fragment'
      return $archive . '/source/' . $fragment;
    }
  }
}

/**
 * builds information about a physical file location, including the archives it belongs in, filename, extension, etc
 * @param $location the file path 
 * @return an array with the path information
 */
function oaff_get_path_info($location) {
  $oaff_path_info = array();
  $oaff_path_info['location'] = $location;
  $oaff_config = variable_get('oaff_config');
  $docbases = $oaff_config['docbases'];

  // location format is <group-name>/<archive-name>/<dimension>/<fragment path>
  $pathinfo = pathinfo($location);
  $module = $pathinfo['filename'];
  $oaff_path_info['module'] = $module;

  $filename = $pathinfo['basename']; 
  $oaff_path_info['filename'] = $filename;
  
  if (isset($pathinfo['extension'])) {
    $oaff_path_info['extension'] = $pathinfo['extension'];
  }
  $lang = 'und'; // default;
  $mod_pathinfo = pathinfo($module);
  $oaff_path_info['base_module'] = $mod_pathinfo['filename'];
  if (isset($mod_pathinfo['extension'])) {
    $lang = $mod_pathinfo['extension'];
  }
  $oaff_path_info['lang'] = $lang;

  $parent = dirname($location);
  $oaff_path_info['parent'] = $parent; 

  $loc_segs = explode('/', $location);
  
  $oaff_path_info['group'] = $loc_segs[0];
  $oaff_path_info['archive'] = $loc_segs[1];
  $oaff_path_info['dimension'] = $loc_segs[2];
  $oaff_path_info['rel_parent'] = oaff_join_path(array_slice($loc_segs, 3, -1));

  $oaffName = $module; //default
  if ($module != $filename) { //there is an extension
    $oaffName .= '.omdoc';
  }

  // removing 'source' and changing extension to .omdoc
  $alias = oaff_join_path(array($oaff_path_info['group'], $oaff_path_info['archive'], $oaff_path_info['rel_parent'], $oaffName)); 
  
  $oaff_path_info['alias'] = $alias;
  $frag_segs = array_slice($loc_segs, 3);
  if (count($frag_segs) > 0) {
    $frag_segs[count($frag_segs) - 1] = $oaffName;
  }
  $frag_path = oaff_join_path($frag_segs);
  $oaff_path_info['rel_path'] = $frag_path;

  $docbase = "http://mathhub.info/"; // default
  if (isset($oaff_config['archive_id'][$oaff_path_info['group']]) 
    && isset($oaff_config['archive_id'][$oaff_path_info['group']][$oaff_path_info['archive']])) {
    $archive_id = $oaff_config['archive_id'][$oaff_path_info['group']][$oaff_path_info['archive']];
    $docbase = $docbases[$archive_id];
  }
  
  $dpath = oaff_join_path(array($docbase, $frag_path));
  $oaff_path_info['dpath'] = $dpath;
  
  return $oaff_path_info;
}

/**
* Function that returns formated SVG for the given node that can be panned and zoomed
* @param $node The node to generate SVG for
*/
function oaff_node_svg($node) {
  $nid = $node->nid;
  $location = $node->field_external['und']['0']['path'];
  $alias = oaff_get_path_info($location)['alias'];
  oaff_set_breadcrumb($nid, array($nid));
  // script for zoom and pan
  $oaff_path = drupal_get_path('module', 'oaff');
  $svg_script = '/' . $oaff_path . '/scripts/svg-pan-zoom.js';
  drupal_add_js($svg_script, 'file');
  
  // modules
  $inst_id = oaff_initialize($location, oaff_get_node_filter_format($node));

  // activate zoom and pan of SVG
  $activate_pan_zoom = 
    '// Don\'t use window.onLoad like this in production, because it can only listen to one function.
      window.onload = function() {
        // Expose to window namespase for testing purposes
        window.zoomTiger = svgPanZoom(\'#node-svg\', {
          zoomEnabled: true,
          controlIconsEnabled: true,
          fit: true,
          center: true,
          viewportSelector: document.getElementById(\'node-svg\').querySelector(\'#wrapper\')
        });
      };';

  $pathinfo = oaff_get_path_info($location);
  $out = oaff_svg_html($pathinfo);
  $content = 
'   <div id="' . $inst_id . '" style="border:3px solid #5DBCD2; border-radius: 5px;">' . 
        oaff_svg_clean($out) .
'   </div>
    <script>
      ' . $activate_pan_zoom . '    
    </script>';  
  if (isset($_GET['view'])) {
    oaff_generate_blank_page(($node->title) . ' | SVG' , $content);
  } else {
    $out = "<a class=\"btn btn-default btn-sm\" target=\"_blank\" href=\"/" . 
          $alias . "%21svg?view=full\" role=\"button\">Full screen</a>" . $content;
   ; 
    return $out;
  }
}


/**
* Returns SVG as a string where header is replaced to allow panning and zoom functionality
* @param $svg SVG as a string
*/
function oaff_svg_clean($svg) {
  $out = substr($svg, strpos($svg, '<svg'));
  $out = substr($out, strpos($out, '>')+1);
  $out = substr($out, 0, strpos($out, '</svg>'));
  $out = 
      "\n<svg id=\"node-svg\" xmlns=\"http://www.w3.org/2000/svg\" height=\"720px\" width=\"100%\">" .
      "\n<g id=\"wrapper\">" . $out . "\n</g></svg>";
  return $out;
}

/**
* Returns true if access is allowed to the current node
* @param $node The node to check access for
* @param $node_types Array of node types that can be accessed
*/
function oaff_access_by_node_type($node, $node_types) {
  if (array_search($node->type, $node_types) != false) 
    return true;
  return false;
}

/**
* Generates OMDoc of the node
* @param $node The node to get OMDoc for
*/
function oaff_node_omdoc($node) {
  $nid = $node->nid;
  $location = $node->field_external['und']['0']['path'];
  oaff_set_breadcrumb($nid, array($nid));
  // change path extension of file from .* to .omdoc
  $slices = explode('.', strrev($location),2);
  $omdoc_location = strrev($slices[1]) . '.omdoc';
  $omdoc = ""; //default
  if (planetary_repo_stat_file($omdoc_location)) { //omdoc exists
    $omdoc = planetary_repo_load_file($omdoc_location);
  }
  return "<pre>\n" . check_plain($omdoc) . "\n</pre>";
}

/**
* Returns source code of the document of the node
* @param $node The node to get source code for
*/
function oaff_node_source($node) {
  $nid = $node->nid;
  $location = $node->field_external['und']['0']['path'];
  oaff_set_breadcrumb($nid, array($nid));
  $source = planetary_repo_load_file($location);
  $status = oaff_get_errors($nid);
  $output = oaff_mark_source_errors(check_plain($source), $nid, $status);
  return $output; 
}

/**
* @return Javascript for the current node as a string. Should
* be included in the head of the page.
*/
function oaff_get_js_as_string() {
  $scripts = drupal_add_js();
  planetary_libs_js_alter($scripts);
  $base_url = $GLOBALS['base_url'];
  $out = '';
  foreach ($scripts as $key => $script) {
    // ignore drupal related scripts
    if ($key === 'settings' 
      || $key === "misc/drupal.js"
      || $key === "sites/all/modules/devel/devel_krumo_path.js")
      continue;
    switch ($script['type']) {
      case 'external':
        $path = $script['data'];
        $out .= "<script src=\"$path\"></script>\n";
        break;

      case 'file':
        $path = $script['data'];
        if ($path[0] != '/')
          $path = '/' . $path;
        $out .= "<script src=\"{$base_url}{$path}\"></script>\n";
        // add bootstrap manually after jQuery. TODO
        if ($key === 'misc/jquery.js')
          $out .= "<script src=\"//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js\"></script>\n";
        break;

      case 'inline':
        $data = $script['data'];
        $out .= "<script>$data</script>\n";
        break;
      
      default:
        break;
    }
  }
  return $out;
}

/**
* @return CSS for the current node as  a string. Should
* be included in the head of the page.
*/
function oaff_get_css_as_string() {
  $csss = drupal_add_css();
  planetary_libs_css_alter($csss);
  $base_url = $GLOBALS['base_url'];
  // add bootstrap manually after jQuery. TODO
  $out = '<link type="text/css" rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css" media="all" />';
  foreach ($csss as $key => $css) {
    $path = $css['data'];
    // ignore drupal internal css
    if (startsWith($path, 'modules'))
      continue;
    if ($path[0] != '/')
      $path = '/' . $path;
    $out .= "<link type=\"text/css\" rel=\"stylesheet\" href=\"{$base_url}{$path}\" media=\"all\" />\n";
  }
  return $out;
}

/** 
* Generates blank page (page w/o Drupal menu)
* @param $title The title of the new page
* @param $body The content of the body of the page
*/
function oaff_generate_blank_page($title, $body) {
  $out = 
'<!DOCTYPE html>
<html>
  <head>
    <title>' . $title . '</title>' . 
    oaff_get_css_as_string() .
    oaff_get_js_as_string() . '
  </head>
  <body>
  '. $body . '
  </body>
</html>';
  print($out);
}

// -------------------------- OAFF Configuration ------------------------- \\

/**
 * validation function of oaff configuration form
 * @param $form the form to be validated
 * @param $form the form state, including filled in values
 */
function oaff_config_validate($form, &$form_state) {
  $formats_s = $form_state['values']['oaff_archive_formats'];
  $formats_lines = explode("\n", $formats_s);
  foreach ($formats_lines as $line) {
    $pair = explode(' ', $line);
    if (count($pair) != 2) {
      form_set_error('oaff_archive_formats', t('Invalid line "' . $line .  '", must be space-separated pair of archive and text format'));
    }
  }

  $node_types_s = $form_state['values']['oaff_format_node_types'];
  $node_types_lines = explode("\n", $node_types_s);
  foreach ($node_types_lines as $line) {
    $pair = explode(' ', $line);
    if (count($pair) != 2) {
      form_set_error('oaff_format_node_types', t('Invalid line "' . $line .  '", must be space-separated pair of text format and nodetype'));
    }
  }
  
  $extensions_s = $form_state['values']['oaff_format_extensions'];
  $extensions_lines = explode("\n", $extensions_s);
  foreach ($extensions_lines as $line) {
    $pair = explode(' ', $line);
    if (count($pair) != 2) {
      form_set_error('oaff_format_extensions', t('Invalid line "' . $line .  '", must be space-separated pair of format and extension'));
    }
  }
}

/**
 * submit function of the oaff configuration form
 * @param $form the form to be validated
 * @param $form the form state, including filled in values
 */
function oaff_config_submit($form, &$form_state) {
  $formats_s = $form_state['values']['oaff_archive_formats'];
  $node_types_s = $form_state['values']['oaff_format_node_types'];
  $extensions_s = $form_state['values']['oaff_format_extensions'];
  $logging = $form_state['values']['oaff_logging_enabled'];
  
  oaff_config_set($formats_s, $node_types_s, $extensions_s, $logging);
}

/**
 * helper function to set oaff configuration, called by oaff_config_submit and oaff_install
 * @param $formats_S string encoding information of archive - format pairs
 * @param $node_types_S string encoding information of format - node_type pairs
 * @param $extensions_S string encoding information of format - (file) extension pairs
 */
function oaff_config_set($formats_s, $node_types_s, $extensions_s, $logging) {
  $formats_lines = explode("\n", $formats_s);
  $formats = array();
  foreach ($formats_lines as $line) {
    if (trim($line) != '') {
      $pair = explode(' ', $line);
      $formats[trim($pair[0])] = trim($pair[1]);
    }
  }

  $node_types_lines = explode("\n", $node_types_s);
  $node_types = array();
  foreach ($node_types_lines as $line) {
    if (trim($line) != '') {
      $pair = explode(' ', $line);
      $node_types[trim($pair[0])] = trim($pair[1]);
    }
  }

  $extensions_lines = explode("\n", $extensions_s);
  $extensions = array();
  foreach ($extensions_lines as $line) {
    if (trim($line) != '') {   
      $pair = explode(' ', $line);
      $extensions[trim($pair[0])] = trim($pair[1]);
    }
  }
  
  $oaff_config = variable_get('oaff_config');
  $oaff_config['formats'] = $formats;
  $oaff_config['node_types'] = $node_types;
  $oaff_config['extensions'] = $extensions;
  $oaff_config['logging'] = $logging;
  variable_set("oaff_config", $oaff_config);
}

/**
 * OAFF configuration form
 * @param $form the form to be validated
 * @param $form the form state, including filled in values
 * @return the newly built form
 */
function oaff_config_form($form, &$form_state) {
  $form['oaff_archive_formats'] = array(
    '#type' => 'textarea',
    '#title' => t('The Text Format associated with each archive'),
    '#default_value' => variable_get('oaff_archive_formats', ''),
    '#description' => t(' Archive name and its associated text format separated by space. One such pair per line'),
  );

  $form['oaff_format_node_types'] = array(
    '#type' => 'textarea',
    '#title' => t('The content type associated with each text format'),
    '#default_value' => variable_get('oaff_format_node_types', ''),
    '#description' => t('Text format and its associated node type separated by space. One such pair per line'),
  );

  $form['oaff_format_extensions'] = array(
    '#type' => 'textarea',
    '#title' => t('The extension associated with each format'),
    '#default_value' => variable_get('oaff_format_extensions', ''),
    '#description' => t('Text format and its associated extension separated by space. One such pair per line'),
  );

  $form['oaff_logging_enabled'] = array(
     '#type' => 'checkbox',
     '#title' => t("Check to enable logging"),
     '#default_value' => variable_get('oaff_logging_enabled', false),
     '#description' => t('If enabled, mathhub.info admins will see developer-level logs for each page load'),
  );

  $form['#validate'] = array('oaff_config_validate');
  $form['#submit'] = array('oaff_config_submit');

  return system_settings_form($form);
}
// ######################## End OAFF Configuration ######################### \\
